module(load="imtcp")
input(type="imtcp" port="514")
template(name="RemoteLogs" type="string"
    string="/var/log/remote/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%.log")
if $fromhost-ip startswith "192.168.10." then {
    action(type="omfile" dynaFile="RemoteLogs")
    stop
}
