all:
  vars:
    ansible_user: ADMIN_USER
    ansible_ssh_private_key_file: ~/.ssh/HOMELAB_SSH_PRIVATE_KEY
  children:
    linux_vms:
      children:
        infra:
          hosts:
            infra01:
              ansible_host: INFRA01_HOST
        game:
          hosts:
            game01:
              ansible_host: GAME01_HOST
    docker_hosts:
      children:
        infra:
        game:
